image:
  file: .gitpod.Dockerfile

tasks:
  - init: mvn install -DskipTests=false

vscode:
  extensions:
    - redhat.java
    - CucumberOpen.cucumber-official

jetbrains:
    intellij:
        plugins:
            - gherkin
            - cucumber-java
